version: "3"
services:
  api:
      build: .
      volumes:
          - ./users_stub:/opt/users_stub
      ports:
        - "5000:5000"
      depends_on:
        - db
  db:
      image: mongo:latest
      restart: always
